[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install uvicorn[standard]==0.24.0"
]

[phases.build]
cmds = ["python -c 'import uvicorn; print(\"uvicorn installed successfully\")'"]

[start]
cmd = "cd /app && python run.py"
