[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python3.11 -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python3.11 start.py"


